### ISSUE TITLE
How to pass subAccount, globalAccount ?

### ISSUE THREAD

**Issue by suchins3** [SAP/clm-sl-alert-notification-client#42]
Hi,

I am sending alerts to particular sub account, how do we pass resource with client library?
    "resource": {
        "resourceGroup": "**",
        "globalAccount": "**,
        "subAccount": "***"
    }

Thanks

**Comment by ipaunov** [comment]
Hello suchin,
You do not need to pass subaccount and globalaccount, the routing to the particular subaccount is based on the credentials.
We send the event to the subaccount where you created the credentials

Best regards,
Ivan
